collections:
  blog:
    path: blog/
    output: true
    title: Blog
    editor:
      type: html
    fields:
      title:
        type: text
      author:
        type: text
      date:
        type: datetime

media_dir: uploads
