collections_config:
  posts:
    path: _posts/
    output: true
    title: Posts
    filename: "{{ date | date: '%Y-%m-%d' }}-{{ title | slugify }}"
    editor:
      type: markdown
    fields:
      title:
        type: text
      author:
        type: text
      date:
        type: date
      tags:
        type: list

media_dir: uploads
