backend:
  name: github
  repo: your-github-username/your-repo-name
  branch: main
  auth_scope: public_repo

  # Add this for local testing
  api_root: "https://api.github.com"
  site_url: "http://localhost:8080/admin"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog-posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
