backend:
  name: git-gateway
  branch: main
  site_domain: agiletechops-web.netlify.app

media_folder: "assets/blog-media"
public_folder: "/assets/blog-media"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false, hint: "Upload a thumbnail image for this post." }
      - { label: "Body", name: "body", widget: "markdown" }
